# Generated by Django 5.2.8 on 2026-02-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_listener_creator_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="header_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
