# Generated by Django 5.2.8 on 2026-02-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_user_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="header_image_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture_url",
        ),
        migrations.AddField(
            model_name="user",
            name="header_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/headers/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/avatars/"
            ),
        ),
    ]
