# Generated by Django 6.0.2 on 2026-03-01 21:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_track_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tracks/covers/', validators=[accounts.models.validate_image_size]),
        ),
    ]
